### ISSUE TITLE
Option 1 is not working

### ISSUE THREAD

**Issue by prashantpandey9** [abhishekgoyal-a11y/Web-Crawler#1]
While clicking on option 1 its not asking for any url but putting a error saying "Error:- Invalid URL or Internet is not Connected!"

**Comment by abhishekgoyal-a11y** [comment]
Which option 1
Video Crawler or image crawler??

**Comment by prashantpandey9** [comment]
Video Crawler.

**Comment by abhishekgoyal-a11y** [comment]
Which url you have searched?
